language: ruby
env:
  - JSONAPI_RESOURCES_VERSION=0.9 RAILS_VERSION=4.2.0
install:
  - bundle install
rvm:
  - 2.3
  - 2.4
  - 2.5
notifications:
  email: false
script:
  - ./bin/phare
  - bundle exec rake
