language: ruby
cache: bundler
sudo: false
env:
  - JSONAPI_RESOURCES_VERSION=0.7.0 RAILS_VERSION=4.1.0
  - JSONAPI_RESOURCES_VERSION=0.7.0 RAILS_VERSION=4.2.0
  - JSONAPI_RESOURCES_VERSION=0.7.1.beta1 RAILS_VERSION=4.1.0
  - JSONAPI_RESOURCES_VERSION=0.7.1.beta1 RAILS_VERSION=4.2.0
rvm:
  - 2.1.2
before_install: gem install bundler -v 1.11.2
notifications:
  email: false
