language: ruby
rvm:
  - 2.3
gemfile:
  - gemfiles/rails_4_2_pundit_1.gemfile
  - gemfiles/rails_5_0_pundit_1.gemfile
  - gemfiles/rails_5_1_pundit_1.gemfile
  - gemfiles/rails_5_2_pundit_1.gemfile
  - gemfiles/rails_5_2_pundit_2.gemfile
before_install: gem install bundler -v 1.16.2
notifications:
  email: false
script:
  - ./bin/phare
  - bundle exec rake
