language: ruby
branches:
  only:
    - master
rvm:
  - 2.3
gemfile:
  - gemfiles/rails_4_2_pundit_1.gemfile
  - gemfiles/rails_5_0_pundit_1.gemfile
  - gemfiles/rails_5_1_pundit_1.gemfile
  - gemfiles/rails_5_2_pundit_1.gemfile
  - gemfiles/rails_6_0_pundit_1.gemfile
  - gemfiles/rails_4_2_pundit_2.gemfile
  - gemfiles/rails_5_0_pundit_2.gemfile
  - gemfiles/rails_5_1_pundit_2.gemfile
  - gemfiles/rails_5_2_pundit_2.gemfile
  - gemfiles/rails_6_0_pundit_2.gemfile
before_install:
  - gem install bundler -v '< 2'
notifications:
  email: false
script:
  - ./bin/phare
  - bundle exec rake
